# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f <- function(s) {
    .Call(`_exampleXPtr_f`, s)
}

displayHash <- function(a) {
    invisible(.Call(`_exampleXPtr_displayHash`, a))
}

getHash <- function(a, name) {
    .Call(`_exampleXPtr_getHash`, a, name)
}

insertHash <- function(a, name, chr, pos) {
    invisible(.Call(`_exampleXPtr_insertHash`, a, name, chr, pos))
}

newHash <- function() {
    .Call(`_exampleXPtr_newHash`)
}

